import type { InventoryItem, Rarity } from "@/types/content";

export const rarityOrder: readonly Rarity[] = ["legendary", "epic", "rare", "common"];

export const inventory = [
  {
    id: "databricks",
    abbr: "DBX",
    name: "Databricks",
    rarity: "legendary",
    category: "Platform",
    note: "Certified. Lakehouse home base.",
  },
  {
    id: "pyspark",
    abbr: "PYS",
    name: "PySpark",
    rarity: "legendary",
    category: "Processing",
    note: "50M+ row pipelines.",
  },
  {
    id: "sql",
    abbr: "SQL",
    name: "SQL",
    rarity: "legendary",
    category: "Language",
    note: "Advanced. Tuning is the fun part.",
  },
  {
    id: "synapse",
    abbr: "SYN",
    name: "Synapse",
    rarity: "legendary",
    category: "Platform",
    note: "45+ pipelines shipped.",
  },
  {
    id: "adf",
    abbr: "ADF",
    name: "Data Factory",
    rarity: "epic",
    category: "Orchestration",
    note: "Metadata-driven everything.",
  },
  {
    id: "fabric",
    abbr: "FAB",
    name: "MS Fabric",
    rarity: "epic",
    category: "Platform",
    note: "DP-700 certified.",
  },
  {
    id: "delta",
    abbr: "DLT",
    name: "Delta Lake",
    rarity: "epic",
    category: "Storage",
    note: "Medallion layers.",
  },
  {
    id: "python",
    abbr: "PY",
    name: "Python",
    rarity: "epic",
    category: "Language",
    note: "Glue for the whole stack.",
  },
  {
    id: "azure-openai",
    abbr: "AOI",
    name: "Azure OpenAI",
    rarity: "epic",
    category: "AI",
    note: "AI-102 certified.",
  },
  {
    id: "adls",
    abbr: "ADL",
    name: "ADLS Gen2",
    rarity: "rare",
    category: "Storage",
    note: "Where the lake lives.",
  },
  {
    id: "echarts",
    abbr: "ECH",
    name: "ECharts",
    rarity: "rare",
    category: "Viz",
    note: "Self-serve reports.",
  },
  {
    id: "nextjs",
    abbr: "NXT",
    name: "Next.js",
    rarity: "rare",
    category: "Web",
    note: "This site runs on it.",
  },
  {
    id: "claude",
    abbr: "CC",
    name: "Claude Code",
    rarity: "rare",
    category: "AI",
    note: "My full-stack pair.",
  },
  {
    id: "airflow",
    abbr: "AF",
    name: "Airflow",
    rarity: "rare",
    category: "Orchestration",
    note: "DAGs on demand.",
  },
  {
    id: "aws",
    abbr: "GLU",
    name: "AWS Glue",
    rarity: "common",
    category: "Cloud",
    note: "S3 · Glue · Redshift.",
  },
  {
    id: "powerbi",
    abbr: "PBI",
    name: "Power BI",
    rarity: "common",
    category: "Viz",
    note: "Analytics-ready models.",
  },
  {
    id: "azure-sql",
    abbr: "ASQ",
    name: "Azure SQL",
    rarity: "common",
    category: "Database",
    note: "Serving layer.",
  },
  {
    id: "git",
    abbr: "GIT",
    name: "Git",
    rarity: "common",
    category: "Tooling",
    note: "Commit early, commit often.",
  },
] as const satisfies readonly InventoryItem[];

export type InventoryId = (typeof inventory)[number]["id"];

/** How the Armory groups the inventory. Every inventory id appears in exactly one group (tested). */
export const inventoryGroups = [
  { title: "Processing & languages", ids: ["pyspark", "sql", "python"] },
  {
    title: "Data platforms & storage",
    ids: ["databricks", "synapse", "fabric", "delta", "adls", "azure-sql"],
  },
  { title: "Orchestration", ids: ["adf", "airflow"] },
  { title: "AI", ids: ["azure-openai", "claude"] },
  { title: "Viz & web", ids: ["echarts", "powerbi", "nextjs"] },
  { title: "Cloud & tooling", ids: ["aws", "git"] },
] as const satisfies readonly { title: string; ids: readonly InventoryId[] }[];
