export const quickViewCopy = {
  back: "Back to the voyage",
  backHint: "Switch to the interactive version",
  contactLabel: "Contact",
  resumePdf: "Download resume (PDF)",
  resumePage: "View resume page",
  resumePageHref: "/resume/",
  experience: "Experience",
  current: "Current",
  projects: "Projects",
  problem: "Problem",
  outcome: "Outcome",
  skills: "Top skills",
  tools: "Tools",
  certifications: "Certifications",
  education: "Education",
  subProjects: "Projects within this role",
  levelOf: (level: number) => `Level ${level} of 99`,
} as const;
